version: "3.9"

services:
  mongodb:
    image: mongo:6
    container_name: rideshare-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rs_user
      MONGO_INITDB_ROOT_PASSWORD: rs_pass_123
      MONGO_INITDB_DATABASE: rideshare
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
