import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/component/navigation/Navigation";
import COLOUR from "@/util/COLOUR";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(COLOUR.background)

  return (
    <html>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  min-h-screen`}
      >
        <main className="w-screen min-h-screen flex flex-col">
          <Navigation />
          <div className={`mx-auto w-full h-full max-w-7xl bg-[#0059D4]/5 px-16 py-12`}>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
